<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Demo Sites_fa fa-angle-right</name>
   <tag></tag>
   <elementGuidId>903826ce-7425-4218-9952-76229aff11f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-6372']/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-6372 > span.arrow > i.fa.fa-angle-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>619861d8-4c63-42e2-90b5-91efed0e91b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-right</value>
      <webElementGuid>b2d85547-95ce-4eb6-80e1-cdf245e0be73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-6372&quot;)/span[@class=&quot;arrow&quot;]/i[@class=&quot;fa fa-angle-right&quot;]</value>
      <webElementGuid>5159a5af-c937-447c-8eb4-e176a9130af5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-6372']/span/i</value>
      <webElementGuid>c95d7786-0266-472e-8b52-49fe2414f9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span/i</value>
      <webElementGuid>f1c6b99f-0d26-401e-a930-cb315a2221ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
