<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_1686046192878</name>
   <tag></tag>
   <elementGuidId>06199c91-6339-4d6f-9c7a-0cdf0d6e6bdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='My Info']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>50529425-7486-4696-9c75-99184e1024f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1686046192878</value>
      <webElementGuid>879f98f2-bfd8-4ce9-99d7-7a7a9d73ade6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
