<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mouse Actions - Tooltip_textbox</name>
   <tag></tag>
   <elementGuidId>c83b0775-482f-4732-be6b-8f281b8a21da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87d45348-880a-4807-a81b-d848ca3d4415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter First Name</value>
      <webElementGuid>b38e38f2-9bb7-43d4-8a01-e06b0261d946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>885bbe7f-5d1d-49ac-b911-eb198e621cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textbox&quot;)</value>
      <webElementGuid>e769ef71-5684-4d95-be10-3b00c0377dae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textbox']</value>
      <webElementGuid>57d0157b-3f60-4b3c-a604-1d7da7068f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div/div/div/div/div/div/center/input</value>
      <webElementGuid>2c57b115-5f6a-497e-9cb5-6ddc004185c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/input</value>
      <webElementGuid>6500c64b-b1b2-44ce-ad36-9dd5b78e835c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Enter First Name' and @id = 'textbox']</value>
      <webElementGuid>d4bbdbe1-7436-4b70-8ec7-b54857720ab3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
