<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Demo Sites_fa fa-angle-right</name>
   <tag></tag>
   <elementGuidId>d3e819ff-9a68-4a8f-a843-a0df8c1b175b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-6372']/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-6372 > span.arrow > i.fa.fa-angle-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b6631036-d670-474a-ad81-526ec902993d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-right</value>
      <webElementGuid>8d058353-7ccb-4bc7-840e-45360ae2e3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-6372&quot;)/span[@class=&quot;arrow&quot;]/i[@class=&quot;fa fa-angle-right&quot;]</value>
      <webElementGuid>7fefc696-d93c-4b05-bc91-15343b3c56aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-6372']/span/i</value>
      <webElementGuid>5adde21c-f895-49c9-9df1-17eb155edbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span/i</value>
      <webElementGuid>1da4a773-9c6c-4bea-8c1e-f25d9819f480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
