<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Delete_checkmark icon</name>
   <tag></tag>
   <elementGuidId>c7b6c9f0-ea72-41e7-acdf-c5e09aed0031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div[2]/div/table/tfoot/tr/th[2]/span/div[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.checkmark.icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f4080cd9-4bcf-484d-9e09-d1e8a5ecf919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2b2895c1-cfc5-4bd5-84da-8c025ee8a262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark icon</value>
      <webElementGuid>ccac4eb0-c0ec-4a11-a5b4-9bcbe4816a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ui fluid container&quot;]/div[@class=&quot;ui fluid container main-content&quot;]/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;ui celled definition sortable striped table custom-grid&quot;]/tfoot[1]/tr[1]/th[@class=&quot;left aligned&quot;]/span[1]/div[@class=&quot;ui basic icon left attached button&quot;]/i[@class=&quot;checkmark icon&quot;]</value>
      <webElementGuid>86dc65cb-06b7-4257-a674-9adca14c2f2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div[2]/div/table/tfoot/tr/th[2]/span/div[2]/i</value>
      <webElementGuid>edba9af5-af22-47ac-ae5f-87db584c7f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/i</value>
      <webElementGuid>c321be26-8c72-49c8-9e24-5d6a6bd9a059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
