<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Delete_remove icon</name>
   <tag></tag>
   <elementGuidId>fc66edc4-d905-42d4-a325-52b16a7ebccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.remove.icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>210b886b-2581-46d2-a7fe-720535ec2a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>59732983-709a-4629-911e-90860466ca14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>remove icon</value>
      <webElementGuid>77b2e18e-41a3-492d-aafd-221770bec507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;dimmable dimmed&quot;]/div[@class=&quot;ui page modals dimmer transition visible active&quot;]/div[@class=&quot;ui modal transition visible active&quot;]/div[@class=&quot;actions&quot;]/button[@class=&quot;ui red button&quot;]/i[@class=&quot;remove icon&quot;]</value>
      <webElementGuid>6ff288cb-b314-4d81-97f7-91232288c4ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]/i</value>
      <webElementGuid>2177cd18-3147-4296-b9ce-178d25516084</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
