<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_simform14_edit icon</name>
   <tag></tag>
   <elementGuidId>31b0ae14-52e3-4055-8a94-7653a246dc88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div[2]/div/table/tbody/tr/td[4]/a[2]/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ui.icon.inverted.button > i.edit.icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a0f49772-6860-404d-8226-6a73b2166971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>be53007c-edf1-48f3-afff-646938fef5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit icon</value>
      <webElementGuid>42abb476-36a2-4737-b02f-b846a3e52b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ui fluid container&quot;]/div[@class=&quot;ui fluid container main-content&quot;]/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;ui celled definition sortable striped table custom-grid&quot;]/tbody[1]/tr[@class=&quot;active&quot;]/td[@class=&quot;right aligned collapsing options-buttons-container&quot;]/a[2]/button[@class=&quot;ui icon inverted button&quot;]/i[@class=&quot;edit icon&quot;]</value>
      <webElementGuid>76a6e5bb-c94b-48a9-9f3b-2403002851b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div[2]/div/table/tbody/tr/td[4]/a[2]/button/i</value>
      <webElementGuid>6cdaeae3-abcd-4288-8878-456df929b617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/button/i</value>
      <webElementGuid>27da07b4-3ca7-4a88-8719-8def24b4d6f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
