<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Create_edit icon</name>
   <tag></tag>
   <elementGuidId>f8654c81-ad43-4a51-aee7-0d54e923cc7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.edit.icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard-toolbar']/div[2]/div/a/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c06de51e-6be7-4be7-b8cd-40d05ae5abff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5c26e449-3b91-4c5c-bde3-019151523d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit icon</value>
      <webElementGuid>cecfe953-dce3-4771-8fb7-2d1aa184fcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard-toolbar&quot;)/div[@class=&quot;ui right secondary pointing menu toolbar-container&quot;]/div[@class=&quot;item&quot;]/a[1]/button[@class=&quot;ui linkedin button&quot;]/i[@class=&quot;edit icon&quot;]</value>
      <webElementGuid>620ddf12-86da-4d6c-92c6-6dd385a10e2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard-toolbar']/div[2]/div/a/button/i</value>
      <webElementGuid>33e92a37-657a-46b7-9ada-a66714eb4851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button/i</value>
      <webElementGuid>96ad6aa4-3b74-42dd-93d5-2c89c64aa3c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
