<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Form elements_dropdown icon</name>
   <tag></tag>
   <elementGuidId>bb5ad335-f79a-4df2-85ec-594d84c780af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div[2]/div[2]/div/div/div/form/div/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.dropdown.icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>afee17dc-1f00-455d-9004-07881ee7e6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4156657d-0e76-41ae-8944-1b6f9a17ee61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown icon</value>
      <webElementGuid>49faa8e4-5cd3-466f-a970-bc7e3892a515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ui fluid container&quot;]/div[@class=&quot;ui fluid container main-content&quot;]/div[@class=&quot;ui segment&quot;]/div[@class=&quot;ui stretched divided grid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;six wide column&quot;]/form[@class=&quot;ui form&quot;]/div[@class=&quot;fields&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;ui selection dropdown&quot;]/i[@class=&quot;dropdown icon&quot;]</value>
      <webElementGuid>a6adb80c-a578-4ed9-94e8-a3fb1fe7b646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div[2]/div[2]/div/div/div/form/div/div/div/i</value>
      <webElementGuid>513eb064-87ab-400a-a038-fce91fe322f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/i</value>
      <webElementGuid>144718b4-d03d-4256-a0b9-50c39c3498d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
