<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>4e11f3f6-e559-4f8e-b884-72bf24b77ce4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='exit_popup_close']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#exit_popup_close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7755b606-cace-4b4a-b76d-dddda9e3765f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exit_popup_close</value>
      <webElementGuid>dfe603a4-18d5-4111-80d4-bfd585413db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>6df5d610-622e-455a-9003-3e6ba2718ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exit_popup_close&quot;)</value>
      <webElementGuid>5fa6df6a-1374-460c-8246-1aaa8a3bae7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='exit_popup_close']</value>
      <webElementGuid>a3e199af-8df6-4d73-9779-f6f689b60aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exit_popup_dismissed']/div/h2/span</value>
      <webElementGuid>62973c4a-fe6d-469a-93a5-b83a91cdcff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cross Browser Testing Cloud Built WithFor Testers'])[1]/following::span[1]</value>
      <webElementGuid>d282e732-2059-4e56-a00f-3155e08871d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up with Google'])[1]/preceding::span[3]</value>
      <webElementGuid>d6ad5cee-bb1f-48af-9409-7ba2843e779b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up with Email'])[1]/preceding::span[5]</value>
      <webElementGuid>2813ddbb-3304-40d1-accd-a3e6cf362fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2/span</value>
      <webElementGuid>54d3f457-98f3-4fb0-bde1-4a21e51444a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'exit_popup_close' and (text() = '×' or . = '×')]</value>
      <webElementGuid>9e97008b-8b84-414b-8835-10802f3f0a2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
