<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Toggle navigation_icon-bar</name>
   <tag></tag>
   <elementGuidId>66ad1f3f-abae-4fc7-a1cf-480d6a431124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div[2]/div/div/div/button/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>35f357d7-cd9c-49c5-b0c7-98fbf901223c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-bar</value>
      <webElementGuid>6e16f236-e7e5-48d0-bfe8-9a6cbe26936d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header_default header_default&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-sm-12 col-xs-12&quot;]/button[@class=&quot;navbar-toggle collapsed hidden-lg hidden-md&quot;]/span[@class=&quot;icon-bar&quot;]</value>
      <webElementGuid>9bf9cc6d-7a15-46d3-8e56-572b65fbead3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div[2]/div/div/div/button/span[3]</value>
      <webElementGuid>9cb8f7f2-369f-494b-a673-22df95110356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>e437825e-2056-45fa-b003-637294393135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
