<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Demo Sites_arrow</name>
   <tag></tag>
   <elementGuidId>97c19227-a281-484d-a91d-1d61ca440352</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-6372']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-6372 > span.arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f27f3afb-908b-4b79-8b33-214f9a49c0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow</value>
      <webElementGuid>ccd442a1-d90f-4b1e-8376-7438abf8d055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-6372&quot;)/span[@class=&quot;arrow&quot;]</value>
      <webElementGuid>20886c76-6d61-45fd-af16-ca2a1ca173fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-6372']/span</value>
      <webElementGuid>ddfb3e7a-bc1e-4f95-83b3-c8f54006b42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo Sites'])[1]/following::span[1]</value>
      <webElementGuid>3038beeb-ab2c-4394-b525-e8c97df825f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A to Z QA Automation Tools Curriculum [27 Modules]'])[1]/following::span[1]</value>
      <webElementGuid>0e6d18dd-bc55-447f-a7a8-7dcb794217cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice Automation'])[1]/preceding::span[1]</value>
      <webElementGuid>31e19ab7-3751-4fbb-9286-5f44082160a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo Site – Registration Form'])[1]/preceding::span[1]</value>
      <webElementGuid>399569a2-18de-4d99-bca3-a80c8324a182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span</value>
      <webElementGuid>a1656208-a835-493f-81db-f27d5084201c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
