<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_00</name>
   <tag></tag>
   <elementGuidId>26811a56-1c9c-410d-85bd-1299794457ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-vfb-16-min-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-vfb-16-min-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bf65706e-86ca-4994-b6af-a24170705313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>3f9f8c6b-dc3b-4a14-94d6-8a7f0262a7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-vfb-16-min-container</value>
      <webElementGuid>26c4f6a4-80ae-41cd-afd3-6aa38facf203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>3d952539-3c40-4f4e-931f-ac7060a59804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e9c09d8-6bdb-497f-9c47-690f905df106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>00</value>
      <webElementGuid>b22c0ce1-9b00-4fdc-ae93-7b01a46b12ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>00</value>
      <webElementGuid>7de9ae78-11be-4469-8d22-00f2f8647eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-vfb-16-min-container&quot;)</value>
      <webElementGuid>d4e2a3a9-dd56-4411-b5bf-71782bf99f1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-vfb-16-min-container']</value>
      <webElementGuid>fb157a6a-99b4-4840-a090-ef9400ec72af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-16']/span[2]/span/span/span/span</value>
      <webElementGuid>a70cb8bc-9f70-4f8e-ad1d-86bdd7111657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HH'])[1]/following::span[5]</value>
      <webElementGuid>1f849cb9-3eae-4467-b528-681f5393ed80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convenient Time'])[1]/following::span[12]</value>
      <webElementGuid>3e9afa93-ccf6-4cdd-872a-d15133a0d413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MM'])[1]/preceding::span[3]</value>
      <webElementGuid>f3bee73c-ac38-441c-9a1e-2ef31590da62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Number'])[1]/preceding::span[3]</value>
      <webElementGuid>13a7467d-0e9c-4071-8267-567ce2177c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/span/span</value>
      <webElementGuid>d7382502-49db-47aa-9736-b6dbd6e34bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-vfb-16-min-container' and @title = '00' and (text() = '00' or . = '00')]</value>
      <webElementGuid>2de60bb5-00e6-48bf-ba60-b58dd83a53c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
